services:
  iteos:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace/ITEOS
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      PORTER_ALLOW_DOCKER_HOST_ACCESS: "true"
    volumes:
      - ..:/workspace/ITEOS
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
